module ordered_priority_queue_dut_sv (
  input  logic [35:0] asi_ingress_0_data,
  input  logic [0:0]  asi_ingress_0_valid,
  input  logic [1:0]  asi_ingress_0_channel,
  input  logic [0:0]  asi_ingress_0_startofpacket,
  input  logic [0:0]  asi_ingress_0_endofpacket,
  input  logic [2:0]  asi_ingress_0_error,
  input  logic [35:0] asi_ingress_1_data,
  input  logic [0:0]  asi_ingress_1_valid,
  input  logic [1:0]  asi_ingress_1_channel,
  input  logic [0:0]  asi_ingress_1_startofpacket,
  input  logic [0:0]  asi_ingress_1_endofpacket,
  input  logic [2:0]  asi_ingress_1_error,
  output logic [35:0] aso_egress_data,
  output logic        aso_egress_valid,
  input  logic        aso_egress_ready,
  output logic        aso_egress_startofpacket,
  output logic        aso_egress_endofpacket,
  output logic [2:0]  aso_egress_error,
  input  logic        d_clk,
  input  logic        d_reset
);
  ordered_priority_queue_dut u_vhdl (
    .asi_ingress_0_data(asi_ingress_0_data),
    .asi_ingress_0_valid(asi_ingress_0_valid),
    .asi_ingress_0_channel(asi_ingress_0_channel),
    .asi_ingress_0_startofpacket(asi_ingress_0_startofpacket),
    .asi_ingress_0_endofpacket(asi_ingress_0_endofpacket),
    .asi_ingress_0_error(asi_ingress_0_error),
    .asi_ingress_1_data(asi_ingress_1_data),
    .asi_ingress_1_valid(asi_ingress_1_valid),
    .asi_ingress_1_channel(asi_ingress_1_channel),
    .asi_ingress_1_startofpacket(asi_ingress_1_startofpacket),
    .asi_ingress_1_endofpacket(asi_ingress_1_endofpacket),
    .asi_ingress_1_error(asi_ingress_1_error),
    .aso_egress_data(aso_egress_data),
    .aso_egress_valid(aso_egress_valid),
    .aso_egress_ready(aso_egress_ready),
    .aso_egress_startofpacket(aso_egress_startofpacket),
    .aso_egress_endofpacket(aso_egress_endofpacket),
    .aso_egress_error(aso_egress_error),
    .d_clk(d_clk),
    .d_reset(d_reset)
  );
endmodule
