

load [file join [pwd] dislin.so]
#load dislin.so

# //////////////////////////////
# // sim lvds error 
# //////////////////////////////
# @berief           simulation of the lvds control error handling
# @content          1) error recovery time after bit slip has occured.



# //////////////////////////////
# // 1) error recovery time
# //////////////////////////////
# @description      The bit slip will shift the word boundary from original (bnd0) to a random new boundary (bnd1).
#                   It is possible for the word boundary to shift again before lvds controller has recovered from
#                   such error.
#                   The simulation is meant for estimating the number of resulting symbol errors for given controller 
#                   error handling strategy. 

# -----------------------------------------------------------------------------
# @brief            genereate error based on a random number 
# @param            err_prob - probability of transition of boundary
#                   len - length (in bit) of the output list
# @output           bnd - list word boundary (0-9). ex: 0 0 0 0 1 1 1 9 9 ...
# -----------------------------------------------------------------------------
proc slip_generator { err_prob len } {

    set ret [list]
    set bnd [expr round(rand()*10)]

    for { set i 0 } { $i < $len } { incr i } {
        if { [expr rand() < $err_prob] } {
            # 1) change boundary
            lappend ret [expr round(rand()*10)]
            set bnd [lindex $ret end]
        } else {
            # 2) do not change
            lappend ret $bnd
        }
    }

    return $ret
}
# -----------------------------------------------------------------------------
# @berief           simulate the [standard] lvds controller in react to bit slip
# @description      sink words streams with boundary (0-9)
#                   source word streams with boundary (0-9)
#
#                   find word boundary based on bit-slip (select bit boundary -> monitor -> count sync pattern)
#                   if no enough sync pattern found, select another boundary
# @input            <bnds> - boundary string generated by the slip generator
#                   <ber> - bit error rate (only for statistics calculation)
#                   <sat> - saturation ratio of link (idle/data+idle)
# -----------------------------------------------------------------------------
proc controller_std { bnds ber sat } {
    #set sat 0.3; # range: [0-1] the link saturation ratio. affects the number of idle words for sync pattern count. for example, more data means less idle words.
              # at 1: the controller is out of control, meaning just random seek boundary without check sync count.
    set req 4; # the required sync pattern count to lock within a window
    set bnd [expr round(rand()*10)]; # the init boundary is random 
    set wnd_sz [expr 4096]
    set n [expr 0]
    set stats(good) [expr 0]
    set stats(bad) [expr 0] 
    set log [open mylog.log w]
    #set st [open mystat.log w]
    #close $st
    set st [open mystat.log a]

    puts ">>>>>>>> init boundary : $bnd"

    while { 1 } {

        # calculate window left and right boundaries
        set wndl [expr $wnd_sz*$n]
        set wndr [expr $wnd_sz*($n + 1) - 1]

        # break when no bnd is left to monitor
        if {$wndl > [llength $bnds]} {
            break
        }

        # partition the boundary list. ex: [0:4095] ...
        set mnt [lrange $bnds $wndl $wndr]

        # count the words with correct boundary
        set cnt [llength [lsearch -all $mnt $bnd]] 
        # deduce number of sync pattern out of sync + data
        set syn [expr (1.0-$sat)*$cnt]
        # incr good/bad counts
        incr stats(good) $cnt
        incr stats(bad) [expr $wnd_sz - $cnt]

        # examine monitoring result
        if { $syn >= $req } {
            # 1) success
            puts $log [format "    found (n = %4i | bnd = %4i | counts = %4i)" $n $bnd $cnt]
        } else {
            # 2) fail 
            puts $log [format "not found (n = %4i | bnd = %4i | counts = %4i)" $n $bnd $cnt]
            # advance to another boundary
            set bnd [expr ($bnd + 1) % 10]
        }

        # log status 
        puts $log [format "good / bad  = %8i / %8i" $stats(good)  $stats(bad)]

        incr n
        puts $log ""
    }
    puts $st [format "%.3f %.2e %.2e %s" $sat $ber [expr 1.0*$stats(bad)/($stats(bad)+$stats(good))] "std"]
    close $log
    close $st

    # report
    puts "<<<<<<<< simulation done\n"
    puts "statistics: "
    puts "+-----------------------------------------+"
    puts [format "|%-20s|%-20s|" "good count" "bad count"]
    puts "+--------------------+--------------------+"
    puts [format "|%-20i|%-20i|" $stats(good) $stats(bad)]
    puts "+-----------------------------------------+\n"
    puts "summary: "
    puts [format "link saturation ratio : %.2f %% " [expr 100.0*$sat]]
    puts [format "BER (sink)   : %.2e " $ber]
    puts [format "BER (source) : %.2e " [expr 1.0*$stats(bad)/($stats(bad)+$stats(good))]]
    puts ""

    

    return -code ok
}
# -----------------------------------------------------------------------------
# @brief            simulate the [pro] edition of lvds controller 
# @description
#
# -----------------------------------------------------------------------------
proc controller_pro { bnds ber sat } {
    # 0) init...
    set sel 0; # initial lane selection  
    set locked 0; # locked to correct phase
    set up 150; # upper score limit
    set th 100; # threshold of selection 
    set nlane 10; # number of phase, in case of 1250 Mbps to 125 Mbps, the deser factor = 10 = number of lane to train for
    # init the score of 10 lanes 
    for {set i 0} {$i < $nlane} {incr i} {
        set scores($i) [expr 0]
    }
    

    
    
    set stats(good) [expr 0]
    set stats(bad) [expr 0] 
    
    #set st [open mystat.log w]
    #close $st
    set st [open mystat.log a]
    #close $st

    
    # 1) handle boundary string
    while {1} {
        
        # parse one digit from bnds string
        set boundary [lindex $bnds $i]
        if {[string eq $boundary ""]} {
            break
        }
        #puts [format "boundary : %i" $boundary]
        # record score
        for {set j 0} {$j < $nlane} {incr j} {
            if {[expr $j == $boundary]} {
                if {[expr $scores($j) < $up]} {
                    incr scores($j)
                }
            } else {
                if {[expr $scores($j) > 0]} {
                    incr scores($j) -1
                }
            }
        }
        # tracking the selection...
        set locked 0
        set alias 0
        for {set j 0} {$j < $nlane} {incr j} {
            if {[expr $scores($j) >= $th]} {
                set sel $j
                set locked 1
                incr alias 
            }
        }
        # collect statstics: count the error 
        if {$locked} {
            if {[expr $sel == $boundary]} {
                incr stats(good)
            } else {
                incr stats(bad)
            }
            #puts "LOCKED!!!"
            #parray scores
        } else {
            incr stats(bad)
        }
        # side: alias -> multiple lanes
        if {$alias > 1} {
            puts "ALIASING!!!"
            parray scores

        }

        incr i  
        #parray scores 
    }

    parray stats



    puts $st [format "%.3f %.2e %.2e %s" $sat $ber [expr 1.0*$stats(bad)/($stats(bad)+$stats(good))] "pro"]
    close $st
    set log [open mylog.log w]
    close $log
}


# main program: 
# refresh the stat log
set st [open mystat.log w]
close $st

# set parameters 
set run_length [expr 1e6]
set sat [expr 0.1]
set ber [expr 1e-6]
#set ber [expr 1e-9]
for {set iber [expr 1e-3]} {[expr $iber>=1e-10]} {set iber [expr $iber/10.0]} {
    break
    # run the simulation 
    puts "/////////////////////// std ///////////////////////"
    controller_std [slip_generator $iber $run_length] $iber $sat
    puts "/////////////////////// pro ///////////////////////"
    controller_pro [slip_generator $iber $run_length] $iber $sat 
}
set iteration 1
for {set isat [expr 0.0]} {[expr $isat <= 1-6.0/910]} {set isat [expr $isat + 0.25/$iteration]} {
    # run the simulation 
    puts "/////////////////////// std ///////////////////////"
    controller_std [slip_generator $ber $run_length] $ber $isat 
    puts "/////////////////////// pro ///////////////////////"
    controller_pro [slip_generator $ber $run_length] $ber $isat 
    incr iteration
}



# //////////////////////////////
# // exambles
# //////////////////////////////

# set n 101
# set pi 3.1415926
# set f [expr $pi / 180]
# set step [expr 360.0 / ($n - 1)]

# for { set i 0 } { $i < $n } { incr i } {
#     lappend xray [expr $i * $step]
#     set x [expr $i * $step * $f]
#     lappend y1ray [expr sin ($x)]
#     lappend y2ray [expr cos ($x)]
# }

# Dislin::metafl cons
# Dislin::scrmod revers
# Dislin::disini

# Dislin::complx
# Dislin::pagera

# Dislin::name "what"  X
# Dislin::name "fuck"  Y

# Dislin::axspos 450 1800 
# Dislin::axslen 2200 1200 

# Dislin::labdig -1 X 
# Dislin::ticks 10 XY 

# Dislin::titlin "Demonstration of CURVE"  1
# Dislin::titlin "SIN (X), COS (X)"  3

# set ic [Dislin::intrgb 0.95 0.95 0.95]
# Dislin::axsbgd $ic
# Dislin::graf 0 360 0 90 -1 1 -1 0.5
# Dislin::setrgb 0.7 0.7 0.7
# Dislin::grid 1 1

# Dislin::color fore
# Dislin::height 50
# Dislin::title

# Dislin::color red
# Dislin::curve $xray $y1ray $n
# Dislin::color green
# Dislin::curve $xray $y2ray $n
# Dislin::disfin